### ISSUE TITLE
Missing templates detected "Error TemplateDoesNotExist raised"

### ISSUE THREAD

**Issue by mawuen** [CIGIHub/cigionline#432]
It was seems that some Template are missed in template directory! 
![Screenshot 2020-10-27 at 10 10 58](https://user-images.githubusercontent.com/66859966/97287786-e55b4380-183c-11eb-875c-cbde90960ebd.png)

**Comment by gabrieltanchen** [comment]
Hi Michael, thank you for your interest. This repository is a work in progress and as such there are many portions that are unfinished. If you're looking for a repo to learn from, I recommend taking a look at the [bakery demo](https://github.com/wagtail/bakerydemo) promoted from the Wagtail team.
